/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eugene_andrienko.telepodcast;

import org.junit.Test;
import static org.junit.Assert.*;


public class TelePodcastTest
{
    @Test
    public void appHasAGreeting()
    {
        assertTrue(true);
    }
}
